package vista;

import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import modelo.Imagen;

public class Vista_Imagenes extends javax.swing.JFrame implements Runnable {

    Thread hilo_imagen1;
    int movimientoX_Imgen_botero = 20;
    static int contador = 0;
    
    public Vista_Imagenes() {

        initComponents();
        hilo_imagen1 = new Thread(this);
        hilo_imagen1.start(); // iniciar el hilo
        //distancia de hilo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Imgen_botero = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 175, 71));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imgen_botero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botero.png"))); // NOI18N
        jPanel1.add(Imgen_botero, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 109, 503, 389));

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 39, 175));
        jLabel1.setText("  IMÁGENES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 40, 294, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Imagenes().setVisible(true);
                cambiarImagen();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Imgen_botero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        
        while (movimientoX_Imgen_botero <= 500) {

            try {// exepcion
                Thread.sleep(100);

                Imgen_botero.setBounds(movimientoX_Imgen_botero, 30, Imgen_botero.getWidth(), Imgen_botero.getHeight());// setbounds poner un limite entre el ancho y alto

                movimientoX_Imgen_botero += 15;

            } catch (InterruptedException ex) {
                Logger.getLogger(Instrucciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public static void cambiarImagen() {

        int velocidad = 2; //segundos
        Timer timer; //instancia
        TimerTask ejecutar;

        int velmil = velocidad * 1000;

        Vista_Imagenes imagenes = new Vista_Imagenes(); // se llama al jlbel
        imagenes.setVisible(true);

        ejecutar = new TimerTask() {

            @Override
            public void run() {

                Icon imagen; //instancia de imagen 
                    switch (contador) {

                        case 0:
                            contador = 1;
                            imagen = new ImageIcon(getClass().getResource("/imagenes/autor.png")); //se declara la imagen
                            imagenes.Imgen_botero.setIcon(imagen); // de la instancia imagenes se cambia el jlabel
                            break;

                        case 1:

                        contador = 2;
                        imagen = new ImageIcon(getClass().getResource("/imagenes/maravillas.png")); //se declara la imagen
                        imagenes.Imgen_botero.setIcon(imagen); // de la instancia imagenes se cambia el jlabel
                        break;
                        
                         case 2:
                        contador = 3;
                        imagen = new ImageIcon(getClass().getResource("/imagenes/papa.png")); //se declara la imagen
                        imagenes.Imgen_botero.setIcon(imagen); // de la instancia imagenes se cambia el jlabel
                        break;
                        
                        case 3:
                        contador = 0;
                        imagen = new ImageIcon(getClass().getResource("/imagenes/triunfo.png")); //se declara la imagen
                        imagenes.Imgen_botero.setIcon(imagen); // de la instancia imagenes se cambia el jlabel
                        break;
                        
                        default:
                            System.out.println("No se pudo cargar imágen");
                    }
                }
            
            
        };

        timer = new Timer();
        timer.scheduleAtFixedRate(ejecutar, velmil, velmil); //peridodo de repeticion

    }
}
